<a href="https://colab.research.google.com/github/rutikashinde27/Python/blob/main/PANDAS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
#PANDAS

import numpy as np
import pandas as pd

path = "https://raw.githubusercontent.com/hakimyameen/Datasets/refs/heads/main/fifa_eda.csv"

df = pd.read_csv(path)

df

,ID,Name,Age,Nationality,Overall,Potential,Club,Value,Wage,Preferred Foot,International Reputation,Skill Moves,Position,Joined,Contract Valid Until,Height,Weight,Release Clause
0,158023,L. Messi,31,Argentina,94,94,FC Barcelona,110500.0,565.0,Left,5.0,4.0,RF,2004,2021-01-01,5.583333,159.0,226500.0
1,20801,Cristiano Ronaldo,33,Portugal,94,94,Juventus,77000.0,405.0,Right,5.0,5.0,ST,2018,2022-01-01,6.166667,183.0,127100.0
2,190871,Neymar Jr,26,Brazil,92,93,Paris Saint-Germain,118500.0,290.0,Right,5.0,5.0,LW,2017,2022-01-01,5.750000,150.0,228100.0
3,193080,De Gea,27,Spain,91,93,Manchester United,72000.0,260.0,Right,4.0,1.0,GK,2011,2020-01-01,6.333333,168.0,138600.0
4,192985,K. De Bruyne,27,Belgium,91,92,Manchester City,102000.0,355.0,Right,4.0,4.0,RCM,2015,2023-01-01,5.916667,154.0,196400.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18202,238813,J. Lundstram,19,England,47,65,Crewe Alexandra,60.0,1.0,Right,1.0,2.0,CM,2017,2019-01-01,5.750000,134.0,143.0
18203,243165,N. Christoffersson,19,Sweden,47,63,Trelleborgs FF,60.0,1.0,Right,1.0,2.0,ST,2018,2020-01-01,6.250000,170.0,113.0
18204,241638,B. Worman,16,England,47,67,Cambridge United,60.0,1.0,Right,1.0,2.0,ST,2017,2021-01-01,5.666667,148.0,165.0
18205,246268,D. Walker-Rice,17,England,47,66,Tranmere Rovers,60.0,1.0,Right,1.0,2.0,RW,2018,2019-01-01,5.833333,154.0,143.0
18206,246269,G. Nugent,16,England,46,66,Tranmere Rovers,60.0,1.0,Right,1.0,2.0,CM,2018,2019-01-01,5.833333,176.0,165.0

In [7]:
df.head(3)

,ID,Name,Age,Nationality,Overall,Potential,Club,Value,Wage,Preferred Foot,International Reputation,Skill Moves,Position,Joined,Contract Valid Until,Height,Weight,Release Clause
0,158023,L. Messi,31,Argentina,94,94,FC Barcelona,110500.0,565.0,Left,5.0,4.0,RF,2004,2021-01-01,5.583333,159.0,226500.0
1,20801,Cristiano Ronaldo,33,Portugal,94,94,Juventus,77000.0,405.0,Right,5.0,5.0,ST,2018,2022-01-01,6.166667,183.0,127100.0
2,190871,Neymar Jr,26,Brazil,92,93,Paris Saint-Germain,118500.0,290.0,Right,5.0,5.0,LW,2017,2022-01-01,5.750000,150.0,228100.0

In [8]:
df[:4]

,ID,Name,Age,Nationality,Overall,Potential,Club,Value,Wage,Preferred Foot,International Reputation,Skill Moves,Position,Joined,Contract Valid Until,Height,Weight,Release Clause
0,158023,L. Messi,31,Argentina,94,94,FC Barcelona,110500.0,565.0,Left,5.0,4.0,RF,2004,2021-01-01,5.583333,159.0,226500.0
1,20801,Cristiano Ronaldo,33,Portugal,94,94,Juventus,77000.0,405.0,Right,5.0,5.0,ST,2018,2022-01-01,6.166667,183.0,127100.0
2,190871,Neymar Jr,26,Brazil,92,93,Paris Saint-Germain,118500.0,290.0,Right,5.0,5.0,LW,2017,2022-01-01,5.750000,150.0,228100.0
3,193080,De Gea,27,Spain,91,93,Manchester United,72000.0,260.0,Right,4.0,1.0,GK,2011,2020-01-01,6.333333,168.0,138600.0

In [9]:
df.tail(3)

,ID,Name,Age,Nationality,Overall,Potential,Club,Value,Wage,Preferred Foot,International Reputation,Skill Moves,Position,Joined,Contract Valid Until,Height,Weight,Release Clause
18204,241638,B. Worman,16,England,47,67,Cambridge United,60.0,1.0,Right,1.0,2.0,ST,2017,2021-01-01,5.666667,148.0,165.0
18205,246268,D. Walker-Rice,17,England,47,66,Tranmere Rovers,60.0,1.0,Right,1.0,2.0,RW,2018,2019-01-01,5.833333,154.0,143.0
18206,246269,G. Nugent,16,England,46,66,Tranmere Rovers,60.0,1.0,Right,1.0,2.0,CM,2018,2019-01-01,5.833333,176.0,165.0

In [10]:
df[-3:]

,ID,Name,Age,Nationality,Overall,Potential,Club,Value,Wage,Preferred Foot,International Reputation,Skill Moves,Position,Joined,Contract Valid Until,Height,Weight,Release Clause
18204,241638,B. Worman,16,England,47,67,Cambridge United,60.0,1.0,Right,1.0,2.0,ST,2017,2021-01-01,5.666667,148.0,165.0
18205,246268,D. Walker-Rice,17,England,47,66,Tranmere Rovers,60.0,1.0,Right,1.0,2.0,RW,2018,2019-01-01,5.833333,154.0,143.0
18206,246269,G. Nugent,16,England,46,66,Tranmere Rovers,60.0,1.0,Right,1.0,2.0,CM,2018,2019-01-01,5.833333,176.0,165.0

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18207 entries, 0 to 18206
Data columns (total 18 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   ID                        18207 non-null  int64
 1   Name                      18207 non-null  object
 2   Age                       18207 non-null  int64
 3   Nationality               18207 non-null  object
 4   Overall                   18207 non-null  int64
 5   Potential                 18207 non-null  int64
 6   Club                      17966 non-null  object
 7   Value                     17955 non-null  float64
 8   Wage                      18207 non-null  float64
 9   Preferred Foot            18207 non-null  object
 10  International Reputation  18159 non-null  float64
 11  Skill Moves               18159 non-null  float64
 12  Position                  18207 non-null  object
 13  Joined                    18207 non-null  int64
 14  Contract Valid Until      17918 non-null  object
 15  Height                    18207 non-null  float64
 16  Weight                    18207 non-null  float64
 17  Release Clause            18207 non-null  float64
dtypes: float64(7), int64(5), object(6)
memory usage: 2.5+ MB

In [12]:
df.isna().sum()

ID                            0
Name                          0
Age                           0
Nationality                   0
Overall                       0
Potential                     0
Club                        241
Value                       252
Wage                          0
Preferred Foot                0
International Reputation     48
Skill Moves                  48
Position                      0
Joined                        0
Contract Valid Until        289
Height                        0
Weight                        0
Release Clause                0
dtype: int64

In [13]:
df.isna().sum()/len(df)*100

ID                          0.000000
Name                        0.000000
Age                         0.000000
Nationality                 0.000000
Overall                     0.000000
Potential                   0.000000
Club                        1.323667
Value                       1.384083
Wage                        0.000000
Preferred Foot              0.000000
International Reputation    0.263635
Skill Moves                 0.263635
Position                    0.000000
Joined                      0.000000
Contract Valid Until        1.587302
Height                      0.000000
Weight                      0.000000
Release Clause              0.000000
dtype: float64

In [14]:
df.drop(columns=['ID','Name'])

,Age,Nationality,Overall,Potential,Club,Value,Wage,Preferred Foot,International Reputation,Skill Moves,Position,Joined,Contract Valid Until,Height,Weight,Release Clause
0,31,Argentina,94,94,FC Barcelona,110500.0,565.0,Left,5.0,4.0,RF,2004,2021-01-01,5.583333,159.0,226500.0
1,33,Portugal,94,94,Juventus,77000.0,405.0,Right,5.0,5.0,ST,2018,2022-01-01,6.166667,183.0,127100.0
2,26,Brazil,92,93,Paris Saint-Germain,118500.0,290.0,Right,5.0,5.0,LW,2017,2022-01-01,5.750000,150.0,228100.0
3,27,Spain,91,93,Manchester United,72000.0,260.0,Right,4.0,1.0,GK,2011,2020-01-01,6.333333,168.0,138600.0
4,27,Belgium,91,92,Manchester City,102000.0,355.0,Right,4.0,4.0,RCM,2015,2023-01-01,5.916667,154.0,196400.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18202,19,England,47,65,Crewe Alexandra,60.0,1.0,Right,1.0,2.0,CM,2017,2019-01-01,5.750000,134.0,143.0
18203,19,Sweden,47,63,Trelleborgs FF,60.0,1.0,Right,1.0,2.0,ST,2018,2020-01-01,6.250000,170.0,113.0
18204,16,England,47,67,Cambridge United,60.0,1.0,Right,1.0,2.0,ST,2017,2021-01-01,5.666667,148.0,165.0
18205,17,England,47,66,Tranmere Rovers,60.0,1.0,Right,1.0,2.0,RW,2018,2019-01-01,5.833333,154.0,143.0
18206,16,England,46,66,Tranmere Rovers,60.0,1.0,Right,1.0,2.0,CM,2018,2019-01-01,5.833333,176.0,165.0

In [15]:
df.drop(columns=['ID'],inplace=True)

In [16]:
df.columns

Index(['Name', 'Age', 'Nationality', 'Overall', 'Potential', 'Club', 'Value',
       'Wage', 'Preferred Foot', 'International Reputation', 'Skill Moves',
       'Position', 'Joined', 'Contract Valid Until', 'Height', 'Weight',
       'Release Clause'],
      dtype='object')

In [ ]:
#Part 2 Pandas

In [1]:

path = "https://raw.githubusercontent.com/hakimyameen/Datasets/refs/heads/main/fifa_eda.csv"

df = pd.read_csv(path)

df

NameError: name 'pd' is not defined

In [2]:
#PANDAS

import numpy as np
import pandas as pd

path = "https://raw.githubusercontent.com/hakimyameen/Datasets/refs/heads/main/fifa_eda.csv"

df = pd.read_csv(path)

df

,ID,Name,Age,Nationality,Overall,Potential,Club,Value,Wage,Preferred Foot,International Reputation,Skill Moves,Position,Joined,Contract Valid Until,Height,Weight,Release Clause
0,158023,L. Messi,31,Argentina,94,94,FC Barcelona,110500.0,565.0,Left,5.0,4.0,RF,2004,2021-01-01,5.583333,159.0,226500.0
1,20801,Cristiano Ronaldo,33,Portugal,94,94,Juventus,77000.0,405.0,Right,5.0,5.0,ST,2018,2022-01-01,6.166667,183.0,127100.0
2,190871,Neymar Jr,26,Brazil,92,93,Paris Saint-Germain,118500.0,290.0,Right,5.0,5.0,LW,2017,2022-01-01,5.750000,150.0,228100.0
3,193080,De Gea,27,Spain,91,93,Manchester United,72000.0,260.0,Right,4.0,1.0,GK,2011,2020-01-01,6.333333,168.0,138600.0
4,192985,K. De Bruyne,27,Belgium,91,92,Manchester City,102000.0,355.0,Right,4.0,4.0,RCM,2015,2023-01-01,5.916667,154.0,196400.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18202,238813,J. Lundstram,19,England,47,65,Crewe Alexandra,60.0,1.0,Right,1.0,2.0,CM,2017,2019-01-01,5.750000,134.0,143.0
18203,243165,N. Christoffersson,19,Sweden,47,63,Trelleborgs FF,60.0,1.0,Right,1.0,2.0,ST,2018,2020-01-01,6.250000,170.0,113.0
18204,241638,B. Worman,16,England,47,67,Cambridge United,60.0,1.0,Right,1.0,2.0,ST,2017,2021-01-01,5.666667,148.0,165.0
18205,246268,D. Walker-Rice,17,England,47,66,Tranmere Rovers,60.0,1.0,Right,1.0,2.0,RW,2018,2019-01-01,5.833333,154.0,143.0
18206,246269,G. Nugent,16,England,46,66,Tranmere Rovers,60.0,1.0,Right,1.0,2.0,CM,2018,2019-01-01,5.833333,176.0,165.0

In [3]:
#access single column

df['Nationality']

0        Argentina
1         Portugal
2           Brazil
3            Spain
4          Belgium
           ...
18202      England
18203       Sweden
18204      England
18205      England
18206      England
Name: Nationality, Length: 18207, dtype: object

In [4]:
#approach 2 using dot operator

df.Age

0        31
1        33
2        26
3        27
4        27
         ..
18202    19
18203    19
18204    16
18205    17
18206    16
Name: Age, Length: 18207, dtype: int64

In [5]:
df.columns

Index(['ID', 'Name', 'Age', 'Nationality', 'Overall', 'Potential', 'Club',
       'Value', 'Wage', 'Preferred Foot', 'International Reputation',
       'Skill Moves', 'Position', 'Joined', 'Contract Valid Until', 'Height',
       'Weight', 'Release Clause'],
      dtype='object')

In [6]:
#access more than 1 column [[]]

df[['Age','Club']]

       Age                 Club
0       31         FC Barcelona
1       33             Juventus
2       26  Paris Saint-Germain
3       27    Manchester United
4       27      Manchester City
...    ...                  ...
18202   19      Crewe Alexandra
18203   19       Trelleborgs FF
18204   16     Cambridge United
18205   17      Tranmere Rovers
18206   16      Tranmere Rovers

[18207 rows x 2 columns]

In [7]:
df[['Age','Club']].head(4)

   Age                 Club
0   31         FC Barcelona
1   33             Juventus
2   26  Paris Saint-Germain
3   27    Manchester United

In [10]:
#to access rows and columns we have 2 more options present in pandas
#loc-label based selection
#stop is inclusive

df.loc[:3,:] #[row,column]

,ID,Name,Age,Nationality,Overall,Potential,Club,Value,Wage,Preferred Foot,International Reputation,Skill Moves,Position,Joined,Contract Valid Until,Height,Weight,Release Clause
0,158023,L. Messi,31,Argentina,94,94,FC Barcelona,110500.0,565.0,Left,5.0,4.0,RF,2004,2021-01-01,5.583333,159.0,226500.0
1,20801,Cristiano Ronaldo,33,Portugal,94,94,Juventus,77000.0,405.0,Right,5.0,5.0,ST,2018,2022-01-01,6.166667,183.0,127100.0
2,190871,Neymar Jr,26,Brazil,92,93,Paris Saint-Germain,118500.0,290.0,Right,5.0,5.0,LW,2017,2022-01-01,5.750000,150.0,228100.0
3,193080,De Gea,27,Spain,91,93,Manchester United,72000.0,260.0,Right,4.0,1.0,GK,2011,2020-01-01,6.333333,168.0,138600.0

In [9]:
df.loc[:3,'Name':'Overall'] #[row,column]

                Name  Age Nationality  Overall
0           L. Messi   31   Argentina       94
1  Cristiano Ronaldo   33    Portugal       94
2          Neymar Jr   26      Brazil       92
3             De Gea   27       Spain       91

In [11]:
df.loc[:3,'Club':'Wage'] #[row,column]

                  Club     Value   Wage
0         FC Barcelona  110500.0  565.0
1             Juventus   77000.0  405.0
2  Paris Saint-Germain  118500.0  290.0
3    Manchester United   72000.0  260.0

In [12]:
df.loc[:2,:]

,ID,Name,Age,Nationality,Overall,Potential,Club,Value,Wage,Preferred Foot,International Reputation,Skill Moves,Position,Joined,Contract Valid Until,Height,Weight,Release Clause
0,158023,L. Messi,31,Argentina,94,94,FC Barcelona,110500.0,565.0,Left,5.0,4.0,RF,2004,2021-01-01,5.583333,159.0,226500.0
1,20801,Cristiano Ronaldo,33,Portugal,94,94,Juventus,77000.0,405.0,Right,5.0,5.0,ST,2018,2022-01-01,6.166667,183.0,127100.0
2,190871,Neymar Jr,26,Brazil,92,93,Paris Saint-Germain,118500.0,290.0,Right,5.0,5.0,LW,2017,2022-01-01,5.750000,150.0,228100.0

In [16]:
#Interview Question:
df.loc[:2,['Name','Club','Nationality','Age']]

                Name                 Club Nationality  Age
0           L. Messi         FC Barcelona   Argentina   31
1  Cristiano Ronaldo             Juventus    Portugal   33
2          Neymar Jr  Paris Saint-Germain      Brazil   26

In [18]:
#iloc --> index based selection
#stop is exclusive
df.iloc[:2,:]

,ID,Name,Age,Nationality,Overall,Potential,Club,Value,Wage,Preferred Foot,International Reputation,Skill Moves,Position,Joined,Contract Valid Until,Height,Weight,Release Clause
0,158023,L. Messi,31,Argentina,94,94,FC Barcelona,110500.0,565.0,Left,5.0,4.0,RF,2004,2021-01-01,5.583333,159.0,226500.0
1,20801,Cristiano Ronaldo,33,Portugal,94,94,Juventus,77000.0,405.0,Right,5.0,5.0,ST,2018,2022-01-01,6.166667,183.0,127100.0

In [ ]:
#Interview Question
#Difference between loc and iloc???

In [19]:
df.iloc[:2,:3]

       ID               Name  Age
0  158023           L. Messi   31
1   20801  Cristiano Ronaldo   33

In [20]:
df.iloc[:2,[10,3,1,5]]

   International Reputation Nationality               Name  Potential
0                       5.0   Argentina           L. Messi         94
1                       5.0    Portugal  Cristiano Ronaldo         94

In [22]:
#keep the copy of the original before making the changes
new_df=df.copy()

In [23]:
df.drop(columns=['Club','ID','Name'])

,Age,Nationality,Overall,Potential,Value,Wage,Preferred Foot,International Reputation,Skill Moves,Position,Joined,Contract Valid Until,Height,Weight,Release Clause
0,31,Argentina,94,94,110500.0,565.0,Left,5.0,4.0,RF,2004,2021-01-01,5.583333,159.0,226500.0
1,33,Portugal,94,94,77000.0,405.0,Right,5.0,5.0,ST,2018,2022-01-01,6.166667,183.0,127100.0
2,26,Brazil,92,93,118500.0,290.0,Right,5.0,5.0,LW,2017,2022-01-01,5.750000,150.0,228100.0
3,27,Spain,91,93,72000.0,260.0,Right,4.0,1.0,GK,2011,2020-01-01,6.333333,168.0,138600.0
4,27,Belgium,91,92,102000.0,355.0,Right,4.0,4.0,RCM,2015,2023-01-01,5.916667,154.0,196400.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18202,19,England,47,65,60.0,1.0,Right,1.0,2.0,CM,2017,2019-01-01,5.750000,134.0,143.0
18203,19,Sweden,47,63,60.0,1.0,Right,1.0,2.0,ST,2018,2020-01-01,6.250000,170.0,113.0
18204,16,England,47,67,60.0,1.0,Right,1.0,2.0,ST,2017,2021-01-01,5.666667,148.0,165.0
18205,17,England,47,66,60.0,1.0,Right,1.0,2.0,RW,2018,2019-01-01,5.833333,154.0,143.0
18206,16,England,46,66,60.0,1.0,Right,1.0,2.0,CM,2018,2019-01-01,5.833333,176.0,165.0

In [27]:
#check duplicate records count
print(df.duplicated().sum())

0

In [28]:
#in this dataset we dont have any duplicate record present
#but if any then we can remove them using drop_duplicates()

df.drop_duplicates()

,ID,Name,Age,Nationality,Overall,Potential,Club,Value,Wage,Preferred Foot,International Reputation,Skill Moves,Position,Joined,Contract Valid Until,Height,Weight,Release Clause
0,158023,L. Messi,31,Argentina,94,94,FC Barcelona,110500.0,565.0,Left,5.0,4.0,RF,2004,2021-01-01,5.583333,159.0,226500.0
1,20801,Cristiano Ronaldo,33,Portugal,94,94,Juventus,77000.0,405.0,Right,5.0,5.0,ST,2018,2022-01-01,6.166667,183.0,127100.0
2,190871,Neymar Jr,26,Brazil,92,93,Paris Saint-Germain,118500.0,290.0,Right,5.0,5.0,LW,2017,2022-01-01,5.750000,150.0,228100.0
3,193080,De Gea,27,Spain,91,93,Manchester United,72000.0,260.0,Right,4.0,1.0,GK,2011,2020-01-01,6.333333,168.0,138600.0
4,192985,K. De Bruyne,27,Belgium,91,92,Manchester City,102000.0,355.0,Right,4.0,4.0,RCM,2015,2023-01-01,5.916667,154.0,196400.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18202,238813,J. Lundstram,19,England,47,65,Crewe Alexandra,60.0,1.0,Right,1.0,2.0,CM,2017,2019-01-01,5.750000,134.0,143.0
18203,243165,N. Christoffersson,19,Sweden,47,63,Trelleborgs FF,60.0,1.0,Right,1.0,2.0,ST,2018,2020-01-01,6.250000,170.0,113.0
18204,241638,B. Worman,16,England,47,67,Cambridge United,60.0,1.0,Right,1.0,2.0,ST,2017,2021-01-01,5.666667,148.0,165.0
18205,246268,D. Walker-Rice,17,England,47,66,Tranmere Rovers,60.0,1.0,Right,1.0,2.0,RW,2018,2019-01-01,5.833333,154.0,143.0
18206,246269,G. Nugent,16,England,46,66,Tranmere Rovers,60.0,1.0,Right,1.0,2.0,CM,2018,2019-01-01,5.833333,176.0,165.0

In [29]:
#add a new column in existing dataframe

df['New_Name']='Rutika'
df

,ID,Name,Age,Nationality,Overall,Potential,Club,Value,Wage,Preferred Foot,International Reputation,Skill Moves,Position,Joined,Contract Valid Until,Height,Weight,Release Clause,New_Name
0,158023,L. Messi,31,Argentina,94,94,FC Barcelona,110500.0,565.0,Left,5.0,4.0,RF,2004,2021-01-01,5.583333,159.0,226500.0,Rutika
1,20801,Cristiano Ronaldo,33,Portugal,94,94,Juventus,77000.0,405.0,Right,5.0,5.0,ST,2018,2022-01-01,6.166667,183.0,127100.0,Rutika
2,190871,Neymar Jr,26,Brazil,92,93,Paris Saint-Germain,118500.0,290.0,Right,5.0,5.0,LW,2017,2022-01-01,5.750000,150.0,228100.0,Rutika
3,193080,De Gea,27,Spain,91,93,Manchester United,72000.0,260.0,Right,4.0,1.0,GK,2011,2020-01-01,6.333333,168.0,138600.0,Rutika
4,192985,K. De Bruyne,27,Belgium,91,92,Manchester City,102000.0,355.0,Right,4.0,4.0,RCM,2015,2023-01-01,5.916667,154.0,196400.0,Rutika
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18202,238813,J. Lundstram,19,England,47,65,Crewe Alexandra,60.0,1.0,Right,1.0,2.0,CM,2017,2019-01-01,5.750000,134.0,143.0,Rutika
18203,243165,N. Christoffersson,19,Sweden,47,63,Trelleborgs FF,60.0,1.0,Right,1.0,2.0,ST,2018,2020-01-01,6.250000,170.0,113.0,Rutika
18204,241638,B. Worman,16,England,47,67,Cambridge United,60.0,1.0,Right,1.0,2.0,ST,2017,2021-01-01,5.666667,148.0,165.0,Rutika
18205,246268,D. Walker-Rice,17,England,47,66,Tranmere Rovers,60.0,1.0,Right,1.0,2.0,RW,2018,2019-01-01,5.833333,154.0,143.0,Rutika
18206,246269,G. Nugent,16,England,46,66,Tranmere Rovers,60.0,1.0,Right,1.0,2.0,CM,2018,2019-01-01,5.833333,176.0,165.0,Rutika

In [ ]:
#add a new row in existing dataframe

In [3]:
import numpy as np
import pandas as pd

path = "/content/CO2 Emissions_Canada.csv"

c = pd.read_csv(path)

c

,Make,Model,Vehicle Class,Engine Size(L),Cylinders,Transmission,Fuel Type,Fuel Consumption City (L/100 km),Fuel Consumption Hwy (L/100 km),Fuel Consumption Comb (L/100 km),Fuel Consumption Comb (mpg),CO2 Emissions(g/km)
0,ACURA,ILX,COMPACT,2.0,4,AS5,Z,9.9,6.7,8.5,33,196
1,ACURA,ILX,COMPACT,2.4,4,M6,Z,11.2,7.7,9.6,29,221
2,ACURA,ILX HYBRID,COMPACT,1.5,4,AV7,Z,6.0,5.8,5.9,48,136
3,ACURA,MDX 4WD,SUV - SMALL,3.5,6,AS6,Z,12.7,9.1,11.1,25,255
4,ACURA,RDX AWD,SUV - SMALL,3.5,6,AS6,Z,12.1,8.7,10.6,27,244
...,...,...,...,...,...,...,...,...,...,...,...,...
7380,VOLVO,XC40 T5 AWD,SUV - SMALL,2.0,4,AS8,Z,10.7,7.7,9.4,30,219
7381,VOLVO,XC60 T5 AWD,SUV - SMALL,2.0,4,AS8,Z,11.2,8.3,9.9,29,232
7382,VOLVO,XC60 T6 AWD,SUV - SMALL,2.0,4,AS8,Z,11.7,8.6,10.3,27,240
7383,VOLVO,XC90 T5 AWD,SUV - STANDARD,2.0,4,AS8,Z,11.2,8.3,9.9,29,232
7384,VOLVO,XC90 T6 AWD,SUV - STANDARD,2.0,4,AS8,Z,12.2,8.7,10.7,26,248

In [4]:
c.columns

Index(['Make', 'Model', 'Vehicle Class', 'Engine Size(L)', 'Cylinders',
       'Transmission', 'Fuel Type', 'Fuel Consumption City (L/100 km)',
       'Fuel Consumption Hwy (L/100 km)', 'Fuel Consumption Comb (L/100 km)',
       'Fuel Consumption Comb (mpg)', 'CO2 Emissions(g/km)'],
      dtype='object')

In [ ]:
#

In [5]:
c['Make'].unique()

array(['ACURA', 'ALFA ROMEO', 'ASTON MARTIN', 'AUDI', 'BENTLEY', 'BMW',
       'BUICK', 'CADILLAC', 'CHEVROLET', 'CHRYSLER', 'DODGE', 'FIAT',
       'FORD', 'GMC', 'HONDA', 'HYUNDAI', 'INFINITI', 'JAGUAR', 'JEEP',
       'KIA', 'LAMBORGHINI', 'LAND ROVER', 'LEXUS', 'LINCOLN', 'MASERATI',
       'MAZDA', 'MERCEDES-BENZ', 'MINI', 'MITSUBISHI', 'NISSAN',
       'PORSCHE', 'RAM', 'ROLLS-ROYCE', 'SCION', 'SMART', 'SRT', 'SUBARU',
       'TOYOTA', 'VOLKSWAGEN', 'VOLVO', 'GENESIS', 'BUGATTI'],
      dtype=object)

In [6]:
#select only records of BMW
#c.query('expression)
c.query("Make=='BMW'")

,Make,Model,Vehicle Class,Engine Size(L),Cylinders,Transmission,Fuel Type,Fuel Consumption City (L/100 km),Fuel Consumption Hwy (L/100 km),Fuel Consumption Comb (L/100 km),Fuel Consumption Comb (mpg),CO2 Emissions(g/km)
76,BMW,320i,COMPACT,2.0,4,A8,Z,10.0,6.5,8.4,34,193
77,BMW,320i,COMPACT,2.0,4,M6,Z,10.4,6.7,8.7,32,200
78,BMW,320i xDRIVE,COMPACT,2.0,4,A8,Z,10.2,7.0,8.8,32,202
79,BMW,328d xDRIVE,COMPACT,2.0,4,A8,D,7.6,5.5,6.7,42,181
80,BMW,328d xDRIVE TOURING,STATION WAGON - SMALL,2.0,4,A8,D,7.6,5.5,6.7,42,181
...,...,...,...,...,...,...,...,...,...,...,...,...
6635,BMW,X7 xDrive40i,SUV - STANDARD,3.0,6,AS8,Z,12.0,9.4,10.8,26,254
6636,BMW,X7 xDrive50i,SUV - STANDARD,4.4,8,AS8,Z,15.5,11.4,13.6,21,318
6637,BMW,X7 M50i,SUV - STANDARD,4.4,8,AS8,Z,15.5,11.4,13.6,21,318
6638,BMW,Z4 sDrive30i,TWO-SEATER,2.0,4,AS8,Z,9.5,7.4,8.5,33,200
6639,BMW,Z4 M40i,TWO-SEATER,3.0,6,AS8,Z,10.3,8.0,9.3,30,216

In [7]:
c.query("Make=='BMW' and Cylinders>6")

,Make,Model,Vehicle Class,Engine Size(L),Cylinders,Transmission,Fuel Type,Fuel Consumption City (L/100 km),Fuel Consumption Hwy (L/100 km),Fuel Consumption Comb (L/100 km),Fuel Consumption Comb (mpg),CO2 Emissions(g/km)
103,BMW,550i xDRIVE,MID-SIZE,4.4,8,A8,Z,14.4,9.6,12.2,23,281
104,BMW,550i xDRIVE GRAN TURISMO,FULL-SIZE,4.4,8,A8,Z,15.0,9.8,12.7,22,292
106,BMW,650i xDRIVE CABRIOLET,SUBCOMPACT,4.4,8,A8,Z,15.0,9.8,12.7,22,292
107,BMW,650i xDRIVE COUPE,COMPACT,4.4,8,A8,Z,14.4,9.6,12.2,23,281
108,BMW,650i xDRIVE GRAN COUPE,COMPACT,4.4,8,A8,Z,15.0,9.8,12.7,22,292
...,...,...,...,...,...,...,...,...,...,...,...,...
6631,BMW,X5 xDrive50i,SUV - STANDARD,4.4,8,AS8,Z,14.5,10.7,12.8,22,302
6632,BMW,X5 M50i,SUV - STANDARD,4.4,8,AS8,Z,14.5,10.7,12.8,22,302
6634,BMW,X6 M50i,SUV - STANDARD,4.4,8,AS8,Z,14.5,10.7,12.8,22,302
6636,BMW,X7 xDrive50i,SUV - STANDARD,4.4,8,AS8,Z,15.5,11.4,13.6,21,318
6637,BMW,X7 M50i,SUV - STANDARD,4.4,8,AS8,Z,15.5,11.4,13.6,21,318

In [9]:
c.query("Make == 'BMW' and `Engine Size(L)`>6")

,Make,Model,Vehicle Class,Engine Size(L),Cylinders,Transmission,Fuel Type,Fuel Consumption City (L/100 km),Fuel Consumption Hwy (L/100 km),Fuel Consumption Comb (L/100 km),Fuel Consumption Comb (mpg),CO2 Emissions(g/km)
3436,BMW,M760i xDRIVE,FULL-SIZE,6.6,12,AS8,Z,17.7,11.9,15.1,19,355
4495,BMW,M760i xDRIVE,FULL-SIZE,6.6,12,AS8,Z,17.7,11.9,15.1,19,355
5559,BMW,M760Li xDrive,FULL-SIZE,6.6,12,AS8,Z,17.7,11.9,15.1,19,355
6609,BMW,M760i xDrive Sedan,FULL-SIZE,6.6,12,AS8,Z,17.8,11.9,15.1,19,354

In [10]:
c.query("`Vehicle Class`=='SUV - STANDARD' ")

,Make,Model,Vehicle Class,Engine Size(L),Cylinders,Transmission,Fuel Type,Fuel Consumption City (L/100 km),Fuel Consumption Hwy (L/100 km),Fuel Consumption Comb (L/100 km),Fuel Consumption Comb (mpg),CO2 Emissions(g/km)
43,AUDI,Q7,SUV - STANDARD,3.0,6,AS8,Z,15.1,10.9,13.2,21,304
44,AUDI,Q7 TDI (modified),SUV - STANDARD,3.0,6,AS8,D,12.4,8.7,10.7,26,290
130,BMW,X5 xDRIVE35i,SUV - STANDARD,3.0,6,A8,Z,12.9,8.8,11.1,25,255
131,BMW,X5 xDRIVE50i,SUV - STANDARD,4.4,8,A8,Z,16.3,10.9,13.9,20,320
132,BMW,X6 M,SUV - STANDARD,4.4,8,A6,Z,18.1,13.7,16.1,18,370
...,...,...,...,...,...,...,...,...,...,...,...,...
7339,TOYOTA,Highlander Hybrid AWD,SUV - STANDARD,2.5,4,AV,X,6.7,6.8,6.7,42,158
7340,TOYOTA,Highlander Hybrid AWD Limited/Platinum,SUV - STANDARD,2.5,4,AV,X,6.6,6.8,6.7,42,156
7348,TOYOTA,Sequoia 4WD,SUV - STANDARD,5.7,8,AS6,X,18.5,13.9,16.4,17,385
7383,VOLVO,XC90 T5 AWD,SUV - STANDARD,2.0,4,AS8,Z,11.2,8.3,9.9,29,232
7384,VOLVO,XC90 T6 AWD,SUV - STANDARD,2.0,4,AS8,Z,12.2,8.7,10.7,26,248

In [ ]:
c.query("`Vehicle Class`=='SUV - STANDARD' ")

In [14]:
#Access/Filter data using Indexing
#Boolean Indexing

c[c['Vehicle Class'] == 'FULL-SIZE']

,Make,Model,Vehicle Class,Engine Size(L),Cylinders,Transmission,Fuel Type,Fuel Consumption City (L/100 km),Fuel Consumption Hwy (L/100 km),Fuel Consumption Comb (L/100 km),Fuel Consumption Comb (mpg),CO2 Emissions(g/km)
0,ACURA,ILX,FULL-SIZE,2.0,4,AS5,Z,9.9,6.7,8.5,33,196
1,ACURA,ILX,FULL-SIZE,2.4,4,M6,Z,11.2,7.7,9.6,29,221
2,ACURA,ILX HYBRID,FULL-SIZE,1.5,4,AV7,Z,6.0,5.8,5.9,48,136
3,ACURA,MDX 4WD,FULL-SIZE,3.5,6,AS6,Z,12.7,9.1,11.1,25,255
4,ACURA,RDX AWD,FULL-SIZE,3.5,6,AS6,Z,12.1,8.7,10.6,27,244
...,...,...,...,...,...,...,...,...,...,...,...,...
7380,VOLVO,XC40 T5 AWD,FULL-SIZE,2.0,4,AS8,Z,10.7,7.7,9.4,30,219
7381,VOLVO,XC60 T5 AWD,FULL-SIZE,2.0,4,AS8,Z,11.2,8.3,9.9,29,232
7382,VOLVO,XC60 T6 AWD,FULL-SIZE,2.0,4,AS8,Z,11.7,8.6,10.3,27,240
7383,VOLVO,XC90 T5 AWD,FULL-SIZE,2.0,4,AS8,Z,11.2,8.3,9.9,29,232
7384,VOLVO,XC90 T6 AWD,FULL-SIZE,2.0,4,AS8,Z,12.2,8.7,10.7,26,248

In [15]:
c[c['Make'] == 'ACURA']

,Make,Model,Vehicle Class,Engine Size(L),Cylinders,Transmission,Fuel Type,Fuel Consumption City (L/100 km),Fuel Consumption Hwy (L/100 km),Fuel Consumption Comb (L/100 km),Fuel Consumption Comb (mpg),CO2 Emissions(g/km)
0,ACURA,ILX,FULL-SIZE,2.0,4,AS5,Z,9.9,6.7,8.5,33,196
1,ACURA,ILX,FULL-SIZE,2.4,4,M6,Z,11.2,7.7,9.6,29,221
2,ACURA,ILX HYBRID,FULL-SIZE,1.5,4,AV7,Z,6.0,5.8,5.9,48,136
3,ACURA,MDX 4WD,FULL-SIZE,3.5,6,AS6,Z,12.7,9.1,11.1,25,255
4,ACURA,RDX AWD,FULL-SIZE,3.5,6,AS6,Z,12.1,8.7,10.6,27,244
...,...,...,...,...,...,...,...,...,...,...,...,...
6508,ACURA,RDX AWD A-SPEC,FULL-SIZE,2.0,4,AS10,Z,11.3,9.1,10.3,27,241
6509,ACURA,RLX Hybrid,FULL-SIZE,3.5,6,AM7,Z,8.4,8.2,8.4,34,196
6510,ACURA,TLX A-SPEC,FULL-SIZE,2.4,4,AM8,Z,10.2,7.4,8.9,32,209
6511,ACURA,TLX SH-AWD,FULL-SIZE,3.5,6,AS9,Z,11.4,7.7,9.8,29,228
6512,ACURA,TLX SH-AWD A-SPEC/Limited Edition,FULL-SIZE,3.5,6,AS9,Z,12.0,8.2,10.3,27,240

In [16]:
c[:1]

,Make,Model,Vehicle Class,Engine Size(L),Cylinders,Transmission,Fuel Type,Fuel Consumption City (L/100 km),Fuel Consumption Hwy (L/100 km),Fuel Consumption Comb (L/100 km),Fuel Consumption Comb (mpg),CO2 Emissions(g/km)
0,ACURA,ILX,FULL-SIZE,2.0,4,AS5,Z,9.9,6.7,8.5,33,196

In [19]:
#use bitwise & operator as we have multiple True False comparison
#logical and wont work here as it is only for single comparison

c[(c['Make']=='ACURA') & (c['Cylinders']==6)]

,Make,Model,Vehicle Class,Engine Size(L),Cylinders,Transmission,Fuel Type,Fuel Consumption City (L/100 km),Fuel Consumption Hwy (L/100 km),Fuel Consumption Comb (L/100 km),Fuel Consumption Comb (mpg),CO2 Emissions(g/km)
3,ACURA,MDX 4WD,FULL-SIZE,3.5,6,AS6,Z,12.7,9.1,11.1,25,255
4,ACURA,RDX AWD,FULL-SIZE,3.5,6,AS6,Z,12.1,8.7,10.6,27,244
5,ACURA,RLX,FULL-SIZE,3.5,6,AS6,Z,11.9,7.7,10.0,28,230
6,ACURA,TL,FULL-SIZE,3.5,6,AS6,Z,11.8,8.1,10.1,28,232
7,ACURA,TL AWD,FULL-SIZE,3.7,6,AS6,Z,12.8,9.0,11.1,25,255
8,ACURA,TL AWD,FULL-SIZE,3.7,6,M6,Z,13.4,9.5,11.6,24,267
11,ACURA,TSX,FULL-SIZE,3.5,6,AS5,Z,12.1,8.3,10.4,27,239
1074,ACURA,MDX SH-AWD,FULL-SIZE,3.5,6,AS6,Z,12.7,9.1,11.1,25,255
1075,ACURA,RDX AWD,FULL-SIZE,3.5,6,AS6,Z,12.1,8.7,10.6,27,244
1076,ACURA,RLX,FULL-SIZE,3.5,6,AS6,Z,11.9,7.7,10.0,28,230
1077,ACURA,RLX HYBRID,FULL-SIZE,3.5,6,AM7,Z,8.0,7.5,7.7,37,177
1079,ACURA,TLX,FULL-SIZE,3.5,6,AS9,Z,11.2,6.9,9.2,31,212
1080,ACURA,TLX SH-AWD,FULL-SIZE,3.5,6,AS9,Z,11.2,7.5,9.6,29,221
2204,ACURA,MDX SH-AWD,FULL-SIZE,3.5,6,AS9,Z,12.7,9.1,11.1,25,254
2205,ACURA,MDX SH-AWD ELITE,FULL-SIZE,3.5,6,AS9,Z,12.2,9.1,10.7,26,251
2206,ACURA,RDX AWD,FULL-SIZE,3.5,6,AS6,Z,12.4,8.6,10.7,26,249
2207,ACURA,RLX,FULL-SIZE,3.5,6,AS6,Z,11.9,7.7,10.0,28,235
2208,ACURA,RLX HYBRID,FULL-SIZE,3.5,6,AM7,Z,8.0,7.5,7.7,37,180
2210,ACURA,TLX SH-AWD,FULL-SIZE,3.5,6,AS9,Z,11.2,7.5,9.6,29,226
3314,ACURA,MDX SH-AWD,FULL-SIZE,3.5,6,AS9,Z,12.6,9.0,11.0,26,259
3315,ACURA,MDX SH-AWD ELITE,FULL-SIZE,3.5,6,AS9,Z,12.2,9.0,10.7,26,251
3316,ACURA,MDX HYBRID AWD,FULL-SIZE,3.0,6,AM7,Z,9.1,9.0,9.0,31,210
3317,ACURA,NSX,FULL-SIZE,3.5,6,AM9,Z,11.1,10.8,11.0,26,261
3318,ACURA,RDX AWD,FULL-SIZE,3.5,6,AS6,Z,12.4,8.7,10.7,26,250
3319,ACURA,RLX HYBRID,FULL-SIZE,3.5,6,AM7,Z,8.2,7.8,8.1,35,190
3321,ACURA,TLX SH-AWD,FULL-SIZE,3.5,6,AS9,Z,11.2,7.5,9.6,29,226
4372,ACURA,MDX SH-AWD,FULL-SIZE,3.5,6,AS9,Z,12.6,9.0,11.0,26,259
4373,ACURA,MDX SH-AWD ELITE,FULL-SIZE,3.5,6,AS9,Z,12.2,9.0,10.7,26,251
4374,ACURA,MDX HYBRID AWD,FULL-SIZE,3.0,6,AM7,Z,9.1,9.0,9.0,31,210
4375,ACURA,NSX,FULL-SIZE,3.5,6,AM9,Z,11.1,10.8,11.0,26,261
4376,ACURA,RDX AWD,FULL-SIZE,3.5,6,AS6,Z,12.4,8.7,10.7,26,250
4377,ACURA,RLX HYBRID,FULL-SIZE,3.5,6,AM7,Z,8.4,8.2,8.4,34,196
4380,ACURA,TLX SH-AWD,FULL-SIZE,3.5,6,AS9,Z,11.4,7.7,9.8,29,228
4381,ACURA,TLX SH-AWD A-SPEC,FULL-SIZE,3.5,6,AS9,Z,12.0,8.2,10.3,27,240
5455,ACURA,MDX SH-AWD,FULL-SIZE,3.5,6,AS9,Z,12.2,9.0,10.8,26,252
5456,ACURA,MDX SH-AWD A-SPEC,FULL-SIZE,3.5,6,AS9,Z,12.2,9.5,11.0,26,258
5457,ACURA,MDX Hybrid AWD,FULL-SIZE,3.0,6,AM7,Z,9.1,9.0,9.0,31,210
5458,ACURA,NSX,FULL-SIZE,3.5,6,AM9,Z,11.1,10.8,11.0,26,261
5461,ACURA,RLX Hybrid,FULL-SIZE,3.5,6,AM7,Z,8.4,8.2,8.4,34,196
5464,ACURA,TLX SH-AWD,FULL-SIZE,3.5,6,AS9,Z,11.4,7.7,9.8,29,228
5465,ACURA,TLX SH-AWD A-SPEC,FULL-SIZE,3.5,6,AS9,Z,12.0,8.2,10.3,27,240
6504,ACURA,MDX SH-AWD,FULL-SIZE,3.5,6,AS9,Z,12.3,9.2,10.9,26,254
6505,ACURA,MDX SH-AWD A-SPEC,FULL-SIZE,3.5,6,AS9,Z,12.2,9.5,11.0,26,258
6506,ACURA,MDX Hybrid AWD,FULL-SIZE,3.0,6,AM7,Z,9.1,9.0,9.0,31,210
6509,ACURA,RLX Hybrid,FULL-SIZE,3.5,6,AM7,Z,8.4,8.2,8.4,34,196
6511,ACURA,TLX SH-AWD,FULL-SIZE,3.5,6,AS9,Z,11.4,7.7,9.8,29,228
6512,ACURA,TLX SH-AWD A-SPEC/Limited Edition,FULL-SIZE,3.5,6,AS9,Z,12.0,8.2,10.3,27,240

In [ ]:
#Groupby operations

In [20]:
c[:1]

,Make,Model,Vehicle Class,Engine Size(L),Cylinders,Transmission,Fuel Type,Fuel Consumption City (L/100 km),Fuel Consumption Hwy (L/100 km),Fuel Consumption Comb (L/100 km),Fuel Consumption Comb (mpg),CO2 Emissions(g/km)
0,ACURA,ILX,FULL-SIZE,2.0,4,AS5,Z,9.9,6.7,8.5,33,196

In [21]:
c.groupby(['Make'])

In [22]:
list(c.groupby(['Make']))

[(('ACURA',),
         Make                              Model Vehicle Class  Engine Size(L)  \
  0     ACURA                                ILX     FULL-SIZE             2.0
  1     ACURA                                ILX     FULL-SIZE             2.4
  2     ACURA                         ILX HYBRID     FULL-SIZE             1.5
  3     ACURA                            MDX 4WD     FULL-SIZE             3.5
  4     ACURA                            RDX AWD     FULL-SIZE             3.5
  ...     ...                                ...           ...             ...
  6508  ACURA                     RDX AWD A-SPEC     FULL-SIZE             2.0
  6509  ACURA                         RLX Hybrid     FULL-SIZE             3.5
  6510  ACURA                         TLX A-SPEC     FULL-SIZE             2.4
  6511  ACURA                         TLX SH-AWD     FULL-SIZE             3.5
  6512  ACURA  TLX SH-AWD A-SPEC/Limited Edition     FULL-SIZE             3.5

        Cylinders Transmission Fuel Type  Fuel Consumption City (L/100 km)  \
  0             4          AS5         Z                               9.9
  1             4           M6         Z                              11.2
  2             4          AV7         Z                               6.0
  3             6          AS6         Z                              12.7
  4             6          AS6         Z                              12.1
  ...         ...          ...       ...                               ...
  6508          4         AS10         Z                              11.3
  6509          6          AM7         Z                               8.4
  6510          4          AM8         Z                              10.2
  6511          6          AS9         Z                              11.4
  6512          6          AS9         Z                              12.0

        Fuel Consumption Hwy (L/100 km)  Fuel Consumption Comb (L/100 km)  \
  0                                 6.7                               8.5
  1                                 7.7                               9.6
  2                                 5.8                               5.9
  3                                 9.1                              11.1
  4                                 8.7                              10.6
  ...                               ...                               ...
  6508                              9.1                              10.3
  6509                              8.2                               8.4
  6510                              7.4                               8.9
  6511                              7.7                               9.8
  6512                              8.2                              10.3

        Fuel Consumption Comb (mpg)  CO2 Emissions(g/km)
  0                              33                  196
  1                              29                  221
  2                              48                  136
  3                              25                  255
  4                              27                  244
  ...                           ...                  ...
  6508                           27                  241
  6509                           34                  196
  6510                           32                  209
  6511                           29                  228
  6512                           27                  240

  [72 rows x 12 columns]),
 (('ALFA ROMEO',),
              Make                     Model Vehicle Class  Engine Size(L)  \
  12    ALFA ROMEO                        4C     FULL-SIZE             1.8
  1081  ALFA ROMEO                        4C     FULL-SIZE             1.8
  2211  ALFA ROMEO                        4C     FULL-SIZE             1.8
  3322  ALFA ROMEO                        4C     FULL-SIZE             1.8
  3323  ALFA ROMEO                 4C SPIDER     FULL-SIZE             1.8
  3324  ALFA ROMEO                    GIULIA     FULL-SIZE             2.0
  3325  ALFA ROMEO                GIULIA AWD     FULL-SIZE             2.0
  3326  ALFA ROMEO       GIULIA QUADRIFOGLIO     FULL-SIZE             2.9
  4382  ALFA ROMEO                  4C COUPE     FULL-SIZE             1.8
  4383  ALFA ROMEO                 4C SPIDER     FULL-SIZE             1.8
  4384  ALFA ROMEO                    GIULIA     FULL-SIZE             2.0
  4385  ALFA ROMEO                GIULIA AWD     FULL-SIZE             2.0
  4386  ALFA ROMEO       GIULIA QUADRIFOGLIO     FULL-SIZE             2.9
  4387  ALFA ROMEO               STELVIO AWD     FULL-SIZE             2.0
  4388  ALFA ROMEO      STELVIO QUADRIFOGLIO     FULL-SIZE             2.9
  5466  ALFA ROMEO                  4C Coupe     FULL-SIZE             1.8
  5467  ALFA ROMEO                 4C Spider     FULL-SIZE             1.8
  5468  ALFA ROMEO                    Giulia     FULL-SIZE             2.0
  5469  ALFA ROMEO                Giulia AWD     FULL-SIZE             2.0
  5470  ALFA ROMEO       Giulia Quadrifoglio     FULL-SIZE             2.9
  5471  ALFA ROMEO                   Stelvio     FULL-SIZE             2.0
  5472  ALFA ROMEO               Stelvio AWD     FULL-SIZE             2.0
  5473  ALFA ROMEO  Stelvio AWD Quadrifoglio     FULL-SIZE             2.9
  6513  ALFA ROMEO                 4C Spider     FULL-SIZE             1.8
  6514  ALFA ROMEO                    Giulia     FULL-SIZE             2.0
  6515  ALFA ROMEO                Giulia AWD     FULL-SIZE             2.0
  6516  ALFA ROMEO       Giulia Quadrifoglio     FULL-SIZE             2.9
  6517  ALFA ROMEO                   Stelvio     FULL-SIZE             2.0
  6518  ALFA ROMEO               Stelvio AWD     FULL-SIZE             2.0
  6519  ALFA ROMEO  Stelvio AWD Quadrifoglio     FULL-SIZE             2.9

        Cylinders Transmission Fuel Type  Fuel Consumption City (L/100 km)  \
  12            4          AM6         Z                               9.7
  1081          4          AM6         Z                               9.7
  2211          4          AM6         Z                               9.7
  3322          4          AM6         Z                               9.7
  3323          4          AM6         Z                               9.7
  3324          4           A8         Z                              10.0
  3325          4           A8         Z                              10.5
  3326          6           A8         Z                              13.8
  4382          4          AM6         Z                               9.7
  4383          4          AM6         Z                               9.7
  4384          4           A8         Z                              10.0
  4385          4           A8         Z                              10.5
  4386          6           A8         Z                              13.8
  4387          4           A8         Z                              10.8
  4388          6           A8         Z                              14.1
  5466          4          AM6         Z                               9.7
  5467          4          AM6         Z                               9.7
  5468          4           A8         Z                              10.0
  5469          4           A8         Z                              10.5
  5470          6           A8         Z                              13.8
  5471          4           A8         Z                              10.3
  5472          4           A8         Z                              10.8
  5473          6           A8         Z                              14.1
  6513          4          AM6         Z                               9.7
  6514          4           A8         Z                              10.0
  6515          4           A8         Z                              10.5
  6516          6           A8         Z                              13.5
  6517          4           A8         Z                              10.3
  6518          4           A8         Z                              10.8
  6519          6           A8         Z                              13.9

        Fuel Consumption Hwy (L/100 km)  Fuel Consumption Comb (L/100 km)  \
  12                                6.9                               8.4
  1081                              6.9                               8.4
  2211                              6.9                               8.4
  3322                              6.9                               8.4
  3323                              6.9                               8.4
  3324                              7.2                               8.7
  3325                              7.7                               9.2
  3326                              9.6                              11.9
  4382                              6.9                               8.4
  4383                              6.9                               8.4
  4384                              7.2                               8.7
  4385                              7.7                               9.2
  4386                              9.6                              11.9
  4387                              8.3                               9.6
  4388                             10.4                              12.4
  5466                              6.9                               8.4
  5467                              6.9                               8.4
  5468                              7.2                               8.7
  5469                              7.7                               9.2
  5470                              9.6                              11.9
  5471                              8.1                               9.3
  5472                              8.3                               9.6
  5473                             10.4                              12.4
  6513                              6.9                               8.4
  6514                              7.2                               8.7
  6515                              7.7                               9.2
  6516                              9.3                              11.6
  6517                              8.1                               9.3
  6518                              8.3                               9.6
  6519                             10.3                              12.3

        Fuel Consumption Comb (mpg)  CO2 Emissions(g/km)
  12                             34                  193
  1081                           34                  193
  2211                           34                  197
  3322                           34                  197
  3323                           34                  197
  3324                           32                  205
  3325                           31                  217
  3326                           24                  280
  4382                           34                  197
  4383                           34                  197
  4384                           32                  205
  4385                           31                  217
  4386                           24                  280
  4387                           29                  226
  4388                           23                  292
  5466                           34                  197
  5467                           34                  197
  5468                           32                  205
  5469                           31                  217
  5470                           24                  280
  5471                           30                  218
  5472                           29                  226
  5473                           23                  292
  6513                           34                  197
  6514                           32                  205
  6515                           31                  217
  6516                           24                  271
  6517                           30                  218
  6518                           29                  226
  6519                           23                  288  ),
 (('ASTON MARTIN',),
                Make             Model Vehicle Class  Engine Size(L)  Cylinders  \
  13    ASTON MARTIN               DB9     FULL-SIZE             5.9         12
  14    ASTON MARTIN            RAPIDE     FULL-SIZE             5.9         12
  15    ASTON MARTIN        V8 VANTAGE     FULL-SIZE             4.7          8
  16    ASTON MARTIN        V8 VANTAGE     FULL-SIZE             4.7          8
  17    ASTON MARTIN      V8 VANTAGE S     FULL-SIZE             4.7          8
  18    ASTON MARTIN      V8 VANTAGE S     FULL-SIZE             4.7          8
  19    ASTON MARTIN          VANQUISH     FULL-SIZE             5.9         12
  1082  ASTON MARTIN               DB9     FULL-SIZE             5.9         12
  1083  ASTON MARTIN          RAPIDE S     FULL-SIZE             6.0         12
  1084  ASTON MARTIN        V8 VANTAGE     FULL-SIZE             4.7          8
  1085  ASTON MARTIN        V8 VANTAGE     FULL-SIZE             4.7          8
  1086  ASTON MARTIN      V8 VANTAGE S     FULL-SIZE             4.7          8
  1087  ASTON MARTIN      V8 VANTAGE S     FULL-SIZE             4.7          8
  1088  ASTON MARTIN     V12 VANTAGE S     FULL-SIZE             6.0         12
  1089  ASTON MARTIN        VANTAGE GT     FULL-SIZE             4.7          8
  1090  ASTON MARTIN        VANTAGE GT     FULL-SIZE             4.7          8
  1091  ASTON MARTIN          VANQUISH     FULL-SIZE             6.0         12
  2212  ASTON MARTIN            DB9 GT     FULL-SIZE             5.9         12
  2213  ASTON MARTIN          RAPIDE S     FULL-SIZE             6.0         12
  2214  ASTON MARTIN          VANQUISH     FULL-SIZE             6.0         12
  2215  ASTON MARTIN        V8 VANTAGE     FULL-SIZE             4.7          8
  2216  ASTON MARTIN        V8 VANTAGE     FULL-SIZE             4.7          8
  2217  ASTON MARTIN        VANTAGE GT     FULL-SIZE             4.7          8
  2218  ASTON MARTIN        VANTAGE GT     FULL-SIZE             4.7          8
  2219  ASTON MARTIN      V8 VANTAGE S     FULL-SIZE             4.7          8
  2220  ASTON MARTIN      V8 VANTAGE S     FULL-SIZE             4.7          8
  2221  ASTON MARTIN     V12 VANTAGE S     FULL-SIZE             6.0         12
  3327  ASTON MARTIN          DB11 V12     FULL-SIZE             5.2         12
  3328  ASTON MARTIN          RAPIDE S     FULL-SIZE             6.0         12
  3329  ASTON MARTIN          VANQUISH     FULL-SIZE             6.0         12
  3330  ASTON MARTIN     V12 VANTAGE S     FULL-SIZE             6.0         12
  3331  ASTON MARTIN     V12 VANTAGE S     FULL-SIZE             6.0         12
  4389  ASTON MARTIN           DB11 V8     FULL-SIZE             4.0          8
  4390  ASTON MARTIN          DB11 V12     FULL-SIZE             5.2         12
  4391  ASTON MARTIN          RAPIDE S     FULL-SIZE             6.0         12
  4392  ASTON MARTIN          VANQUISH     FULL-SIZE             6.0         12
  5474  ASTON MARTIN           DB11 V8     FULL-SIZE             4.0          8
  5475  ASTON MARTIN          DB11 AMR     FULL-SIZE             5.2         12
  5476  ASTON MARTIN  DBS Superleggera     FULL-SIZE             5.2         12
  5477  ASTON MARTIN        Rapide AMR     FULL-SIZE             6.0         12
  5478  ASTON MARTIN   Vanquish Zagato     FULL-SIZE             6.0         12
  5479  ASTON MARTIN        Vantage V8     FULL-SIZE             4.0          8
  6520  ASTON MARTIN           DB11 V8     FULL-SIZE             4.0          8
  6521  ASTON MARTIN          DB11 AMR     FULL-SIZE             5.2         12
  6522  ASTON MARTIN  DBS Superleggera     FULL-SIZE             5.2         12
  6523  ASTON MARTIN        Vantage V8     FULL-SIZE             4.0          8
  6524  ASTON MARTIN        Vantage V8     FULL-SIZE             4.0          8

       Transmission Fuel Type  Fuel Consumption City (L/100 km)  \
  13             A6         Z                              18.0
  14             A6         Z                              18.0
  15            AM7         Z                              17.4
  16             M6         Z                              18.1
  17            AM7         Z                              17.4
  18             M6         Z                              18.1
  19             A6         Z                              18.0
  1082           A6         Z                              18.0
  1083           A8         Z                              16.8
  1084          AM7         Z                              17.4
  1085           M6         Z                              18.1
  1086          AM7         Z                              17.4
  1087           M6         Z                              18.1
  1088          AM7         Z                              19.5
  1089          AM7         Z                              17.4
  1090           M6         Z                              18.1
  1091           A8         Z                              17.6
  2212           A6         Z                              18.0
  2213           A8         Z                              16.8
  2214           A8         Z                              17.6
  2215          AM7         Z                              17.4
  2216           M6         Z                              18.1
  2217          AM7         Z                              17.4
  2218           M6         Z                              18.1
  2219          AM7         Z                              17.4
  2220           M6         Z                              18.1
  2221          AM7         Z                              19.5
  3327           A8         Z                              15.5
  3328           A8         Z                              16.7
  3329           A8         Z                              17.5
  3330          AM7         Z                              19.4
  3331           M7         Z                              23.2
  4389           A8         Z                              13.0
  4390           A8         Z                              15.5
  4391           A8         Z                              16.7
  4392           A8         Z                              17.5
  5474           A8         Z                              13.0
  5475           A8         Z                              15.5
  5476           A8         Z                              16.4
  5477           A8         Z                              16.7
  5478           A8         Z                              17.5
  5479           A8         Z                              12.7
  6520           A8         Z                              13.0
  6521           A8         Z                              15.5
  6522           A8         Z                              16.4
  6523           A8         Z                              13.1
  6524           M7         Z                              16.7

        Fuel Consumption Hwy (L/100 km)  Fuel Consumption Comb (L/100 km)  \
  13                               12.6                              15.6
  14                               12.6                              15.6
  15                               11.3                              14.7
  16                               12.2                              15.4
  17                               11.3                              14.7
  18                               12.2                              15.4
  19                               12.6                              15.6
  1082                             12.6                              15.6
  1083                             10.9                              14.2
  1084                             11.3                              14.7

In [23]:
#fetch a particular group

c.groupby(['Make']).get_group('TOYOTA')

/tmp/ipykernel_444/2322484765.py:3: FutureWarning: When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.
  c.groupby(['Make']).get_group('TOYOTA')

,Make,Model,Vehicle Class,Engine Size(L),Cylinders,Transmission,Fuel Type,Fuel Consumption City (L/100 km),Fuel Consumption Hwy (L/100 km),Fuel Consumption Comb (L/100 km),Fuel Consumption Comb (mpg),CO2 Emissions(g/km)
970,TOYOTA,4RUNNER (Part-Time 4WD),FULL-SIZE,4.0,6,AS5,X,14.3,11.1,12.9,22,297
971,TOYOTA,4RUNNER 4WD,FULL-SIZE,4.0,6,AS5,X,14.3,11.1,12.9,22,297
972,TOYOTA,AVALON,FULL-SIZE,3.5,6,AS6,X,11.3,7.6,9.6,29,221
973,TOYOTA,CAMRY,FULL-SIZE,2.5,4,AS6,X,9.5,6.6,8.2,34,189
974,TOYOTA,CAMRY,FULL-SIZE,3.5,6,AS6,X,11.1,7.8,9.6,29,221
...,...,...,...,...,...,...,...,...,...,...,...,...
7355,TOYOTA,Tacoma 4WD D-Cab TRD Off-Road/Pro,FULL-SIZE,3.5,6,M6,X,13.8,11.7,12.9,22,300
7356,TOYOTA,Tundra,FULL-SIZE,5.7,8,AS6,X,17.7,13.6,15.9,18,371
7357,TOYOTA,Tundra 4WD,FULL-SIZE,5.7,8,AS6,X,18.0,14.2,16.3,17,381
7358,TOYOTA,Yaris,FULL-SIZE,1.5,4,AS6,X,7.3,5.9,6.6,43,155
7359,TOYOTA,Yaris (SIL),FULL-SIZE,1.5,4,M6,X,7.8,6.1,6.9,41,165